// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire gen -tags "oss"
//go:build !wireinject
// +build !wireinject

package server

import (
	"github.com/InariTheFox/oncall/pkg/api"
	"github.com/InariTheFox/oncall/pkg/api/routing"
	"github.com/InariTheFox/oncall/pkg/registry/background_svcs"
	"github.com/InariTheFox/oncall/pkg/services/apiserver"
	"github.com/InariTheFox/oncall/pkg/services/apiserver/standalone"
	"github.com/InariTheFox/oncall/pkg/setting"
	"github.com/google/wire"
)

// Injectors from wire.go:

func Initialize(cfg *setting.Cfg, opts Options, apiOpts api.ServerOptions) (*Server, error) {
	routeRegisterImpl := routing.ProvideRegister()
	httpServer, err := api.ProvideHTTPServer(apiOpts, cfg, routeRegisterImpl)
	if err != nil {
		return nil, err
	}
	service, err := apiserver.ProvideService(cfg)
	if err != nil {
		return nil, err
	}
	backgroundServiceRegistry := background_svcs.ProvideBackgroundServiceRegistry(httpServer, service)
	server, err := New(opts, cfg, httpServer, backgroundServiceRegistry)
	if err != nil {
		return nil, err
	}
	return server, nil
}

func InitializeForCLI(cfg *setting.Cfg) (Runner, error) {
	runner := NewRunner(cfg)
	return runner, nil
}

func InitializeAPIServerFactory() (standalone.APIServerFactory, error) {
	apiServerFactory := standalone.ProvideAPIServerFactory()
	return apiServerFactory, nil
}

// wire.go:

var wireBasicSet = wire.NewSet(
	New, api.ProvideHTTPServer, routing.ProvideRegister, wire.Bind(new(routing.RouteRegister), new(*routing.RouteRegisterImpl)), apiserver.WireSet,
)

var wireSet = wire.NewSet(
	wireBasicSet,
)

var wireCLISet = wire.NewSet(
	NewRunner,
	wireBasicSet,
)
